#!/usr/bin/env bash
# Scaffold a contract-v2 language module (bead A3c).
#
#   scripts/new-module.sh <lang> --extensions a,b[,c] [--display 'Name'] [--root DIR] [--dry-run]
#
# Creates, and never overwrites (AGENTS.md rule 1):
#   modules/ubs-<lang>.sh                 the module: strict mode, the shared
#                                         library (modules/lib/ubs-common.sh),
#                                         the contract's shared flag core,
#                                         NUL-safe file discovery, two example
#                                         checks, text/json/sarif renderers
#   test-suite/<lang>/buggy/sample.<ext>  one fixture pair and a README saying
#   test-suite/<lang>/clean/sample.<ext>  what each proves
#   test-suite/<lang>/README.md
#   test-suite/manifest.json              two cases appended: <lang>-buggy and <lang>-clean
# and prints the steps that are deliberately NOT applied: adding the language
# to ALL_LANGS/detect_lang in `ubs`, the contract.json entry, checksums.
#
# The generated module passes bash -n, shellcheck -S error, its own two
# manifest cases, and (when it exists) contract_conformance.py (bead A8).
set -euo pipefail

usage(){
  sed -n '2,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//' >&2
  exit 2
}

LANG_NAME=""
EXTS=""
DISPLAY=""
ROOT=""
DRY_RUN=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --extensions=*) EXTS="${1#*=}"; shift;;
    --extensions) EXTS="${2:-}"; shift 2;;
    --display=*) DISPLAY="${1#*=}"; shift;;
    --display) DISPLAY="${2:-}"; shift 2;;
    --root=*) ROOT="${1#*=}"; shift;;
    --root) ROOT="${2:-}"; shift 2;;
    --dry-run) DRY_RUN=1; shift;;
    -h|--help) usage;;
    -*) echo "unknown option: $1" >&2; usage;;
    *) if [[ -z "$LANG_NAME" ]]; then LANG_NAME="$1"; shift; else echo "unexpected argument: $1" >&2; usage; fi;;
  esac
done
[[ -n "$LANG_NAME" && -n "$EXTS" ]] || usage
[[ "$LANG_NAME" =~ ^[a-z][a-z0-9]*$ ]] || { echo "language name must be [a-z][a-z0-9]*: $LANG_NAME" >&2; exit 2; }
[[ "$EXTS" =~ ^[a-z0-9]+(,[a-z0-9]+)*$ ]] || { echo "--extensions must be a comma-separated list of extensions: $EXTS" >&2; exit 2; }
[[ -n "$DISPLAY" ]] || DISPLAY="$LANG_NAME"
if [[ -z "$ROOT" ]]; then
  ROOT="$(cd -- "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
EXT1="${EXTS%%,*}"

MODULE="$ROOT/modules/ubs-${LANG_NAME}.sh"
FIXTURE_DIR="$ROOT/test-suite/${LANG_NAME}"
MANIFEST="$ROOT/test-suite/manifest.json"
LIB="$ROOT/modules/lib/ubs-common.sh"
[[ -f "$LIB" ]] || { echo "missing $LIB: the scaffold needs the shared library next to the modules" >&2; exit 2; }
[[ -f "$MANIFEST" ]] || { echo "missing $MANIFEST" >&2; exit 2; }
for existing in "$MODULE" "$FIXTURE_DIR"; do
  if [[ -e "$existing" ]]; then
    echo "refusing to overwrite $existing (delete or rename it yourself first)" >&2
    exit 1
  fi
done
if jq -e --arg id "${LANG_NAME}-buggy" '.cases[] | select(.id == $id)' "$MANIFEST" >/dev/null 2>&1; then
  echo "refusing: manifest case ${LANG_NAME}-buggy already exists in $MANIFEST" >&2
  exit 1
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  printf 'would create:\n  %s\n  %s/buggy/sample.%s\n  %s/clean/sample.%s\n  %s/README.md\nwould append manifest cases %s-buggy and %s-clean to %s\n' \
    "$MODULE" "$FIXTURE_DIR" "$EXT1" "$FIXTURE_DIR" "$EXT1" "$FIXTURE_DIR" "$LANG_NAME" "$LANG_NAME" "$MANIFEST"
  exit 0
fi

render(){
  # @LANG@ @EXTS@ @EXT1@ @DISPLAY@ placeholders; the template is single-quoted
  # so nothing else is expanded here.
  sed -e "s/@LANG@/${LANG_NAME}/g" -e "s/@EXTS@/${EXTS}/g" -e "s/@EXT1@/${EXT1}/g" -e "s/@DISPLAY@/${DISPLAY}/g"
}

mkdir -p "$FIXTURE_DIR/buggy" "$FIXTURE_DIR/clean"
render >"$MODULE" <<'TEMPLATE'
#!/usr/bin/env bash
# UBS module: @DISPLAY@ (@LANG@). Generated by scripts/new-module.sh on
# contract v2: shared library, shared flag core, NUL-safe discovery, one
# in-memory finding list rendered as text, json and sarif. Replace the two
# example checks with real ones; keep the contract (modules/contract.json).
set -Eeuo pipefail

# Shared primitives (bead A1): locale export, json_escape, format contract,
# NUL-safe file listing. Shipped and checksum-verified next to the modules.
UBS_LIB_CHECKSUM="e14943a9c94d4a80fec5372aa6f3854a682bc37d46e0abff4961cb366e3228b3"
UBS_MODULE_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -n "${UBS_VERIFIED_ASSET_DIR:-}" ]]; then
  if [[ -f "${UBS_VERIFIED_ASSET_DIR}/lib/ubs-common.sh" ]]; then
    UBS_MODULE_LIB_DIR="$UBS_VERIFIED_ASSET_DIR"
  elif [[ -f "${UBS_MODULE_LIB_DIR}/lib/ubs-common.sh" ]]; then
    if [[ "${UBS_ALLOW_UNVERIFIED_HELPERS:-0}" == "1" ]]; then
      echo "warning: UBS_ALLOW_UNVERIFIED_HELPERS=1: using unverified lib at ${UBS_MODULE_LIB_DIR}/lib/ubs-common.sh" >&2
    else
      echo "✗ ${BASH_SOURCE[0]}: lib/ubs-common.sh found at unverified location; refusing to load unverified library (set UBS_ALLOW_UNVERIFIED_HELPERS=1 to override)" >&2
      exit 2
    fi
  fi
fi
if [[ -z "${UBS_VERIFIED_ASSET_DIR:-}" ]]; then
  if [[ "${UBS_ALLOW_UNVERIFIED_HELPERS:-0}" == "1" ]]; then
    : # override allows unverified
  elif [[ -n "${UBS_LIB_CHECKSUM:-}" && -f "${UBS_MODULE_LIB_DIR}/lib/ubs-common.sh" ]]; then
    _lib_sha=""
    if command -v sha256sum >/dev/null 2>&1; then
      _lib_sha="$(sha256sum "${UBS_MODULE_LIB_DIR}/lib/ubs-common.sh" 2>/dev/null | awk '{print $1}')"
    elif command -v shasum >/dev/null 2>&1; then
      _lib_sha="$(shasum -a 256 "${UBS_MODULE_LIB_DIR}/lib/ubs-common.sh" 2>/dev/null | awk '{print $1}')"
    elif command -v openssl >/dev/null 2>&1; then
      _lib_sha="$(openssl dgst -sha256 "${UBS_MODULE_LIB_DIR}/lib/ubs-common.sh" 2>/dev/null | awk '{print $NF}')"
    fi
    if [[ -n "$_lib_sha" && "$_lib_sha" != "$UBS_LIB_CHECKSUM" ]]; then
      echo "✗ ${BASH_SOURCE[0]}: lib/ubs-common.sh failed checksum verification (expected $UBS_LIB_CHECKSUM, got $_lib_sha); refusing to load unverified library (run 'ubs doctor --fix' or reinstall)" >&2
      exit 2
    fi
  fi
fi
if [[ ! -f "${UBS_MODULE_LIB_DIR}/lib/ubs-common.sh" ]]; then
  echo "✗ ${BASH_SOURCE[0]}: missing ${UBS_MODULE_LIB_DIR}/lib/ubs-common.sh (run 'ubs doctor --fix' or reinstall)" >&2
  exit 2
fi
# shellcheck source=lib/ubs-common.sh
source "${UBS_MODULE_LIB_DIR}/lib/ubs-common.sh"
ubs_export_locale

VERSION="0.1.0"
LANGUAGE="@LANG@"
PROJECT_DIR="."
FORMAT="text"
CI_MODE=0
FAIL_ON_WARNING=0
VERBOSE=0
QUIET=0
JOBS=0
INCLUDE_EXT="@EXTS@"
EXCLUDE_GLOBS=""
SKIP_CSV=""
NO_COLOR_FLAG="${NO_COLOR:-}"

usage(){
  cat <<'USAGE'
Usage: ubs-@LANG@.sh [PROJECT_DIR|FILE] [options] [OUTPUT_FILE]

Options:
--format=FMT       text|json|sarif (default: text); jsonl/toon come from the meta-runner
--ci               stable timestamps (UTC ISO8601)
--fail-on-warning  exit non-zero if any warnings or critical
-v, --verbose      print more samples in text mode
-q, --quiet        print only the summary
--no-color         disable ANSI colour
--jobs=N           parallel hint (unused by the example checks)
--exclude=GLOBS    additional path globs to skip (forwarded by the meta-runner)
--include-ext=CSV  extra file extensions to scan (default: @EXTS@)
--skip=CSV         skip category numbers (1 markers, 2 dangerous calls)
--list-categories  print the category table and exit
-h, --help         this help
contract: v2
USAGE
}

OUTPUT_FILE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --format=*) FORMAT="${1#*=}"; ubs_validate_format "$FORMAT"; shift;;
    --format) FORMAT="${2:-}"; ubs_validate_format "$FORMAT"; shift 2;;
    --ci) CI_MODE=1; shift;;
    --fail-on-warning) FAIL_ON_WARNING=1; shift;;
    -v|--verbose) VERBOSE=1; shift;;
    -q|--quiet) QUIET=1; shift;;
    --no-color) NO_COLOR_FLAG=1; shift;;
    --jobs=*) JOBS="${1#*=}"; shift;;
    --exclude=*) EXCLUDE_GLOBS="${1#*=}"; shift;;
    --include-ext=*) INCLUDE_EXT="${INCLUDE_EXT},${1#*=}"; shift;;
    --skip=*) SKIP_CSV="${1#*=}"; shift;;
    --list-categories) printf '1  Code markers (TODO/FIXME/XXX)\n2  Dangerous calls (eval-style)\n'; exit 0;;
    -h|--help) usage; exit 0;;
    -*) echo "unknown option: $1" >&2; usage >&2; exit 2;;
    *) if [[ -e "$1" ]]; then PROJECT_DIR="$1"; else OUTPUT_FILE="$1"; fi; shift;;
  esac
done
: "$JOBS" "$VERBOSE" "$NO_COLOR_FLAG"

skip_category(){ [[ ",${SKIP_CSV}," == *",$1,"* ]]; }
timestamp(){ if [[ "$CI_MODE" -eq 1 ]]; then date -u '+%Y-%m-%dT%H:%M:%SZ'; else date '+%Y-%m-%d %H:%M:%S'; fi; }

# ---- file discovery (NUL-safe, honours the meta-runner's --exclude) -------
FILES=()
if [[ -f "$PROJECT_DIR" ]]; then
  FILES=("$PROJECT_DIR")
else
  while IFS= read -r -d '' f; do FILES+=("$f"); done < <(ubs_list_files "$PROJECT_DIR" --ext "$INCLUDE_EXT" ${EXCLUDE_GLOBS:+--exclude "$EXCLUDE_GLOBS"})
fi
TOTAL_FILES=${#FILES[@]}

# ---- findings: one in-memory list, rendered in every format ----------------
F_SEV=(); F_TITLE=(); F_RULE=(); F_COUNT=(); F_SAMPLES=()   # samples: "file:line:code" joined by \x1f
add_finding(){
  local sev="$1" title="$2" rule="$3" count="$4" samples="$5"
  F_SEV+=("$sev"); F_TITLE+=("$title"); F_RULE+=("$rule"); F_COUNT+=("$count"); F_SAMPLES+=("$samples")
}
# grep_check SEVERITY TITLE RULE_ID REGEX: one finding per matching regex over all files.
grep_check(){
  local sev="$1" title="$2" rule="$3" regex="$4" hits="" count=0 line
  [[ "$TOTAL_FILES" -gt 0 ]] || return 0
  while IFS= read -r line; do
    [[ -n "$line" ]] || continue
    hits="${hits:+$hits$'\x1f'}$line"
    count=$((count + 1))
  done < <(grep -n -H -E -- "$regex" "${FILES[@]}" 2>/dev/null | cut -c1-240 || true)
  [[ "$count" -gt 0 ]] && add_finding "$sev" "$title" "$rule" "$count" "$hits"
  return 0
}

# Example checks — replace with real detectors (keep the rule id grammar
# <lang>.<family>.<name> and the category numbers used by --skip).
skip_category 1 || grep_check info "Code markers left in source" "@LANG@.markers.todo" '\b(TODO|FIXME|XXX)\b'
skip_category 2 || grep_check critical "Dynamic code execution (eval-style call)" "@LANG@.security.eval" '\beval[[:space:]]*\('

CRITICAL=0; WARNING=0; INFO=0
for i in "${!F_SEV[@]}"; do
  case "${F_SEV[$i]}" in critical) CRITICAL=$((CRITICAL + F_COUNT[i]));; warning) WARNING=$((WARNING + F_COUNT[i]));; *) INFO=$((INFO + F_COUNT[i]));; esac
done

# ---- renderers --------------------------------------------------------------
sample_parts(){ # "file:line:code" -> prints file, line, code on three lines
  local s="$1" file line
  file="${s%%:*}"; s="${s#*:}"; line="${s%%:*}"; s="${s#*:}"
  printf '%s\n%s\n%s\n' "$file" "$line" "$s"
}
render_text(){
  # The "(contract v2)" marker is required: the meta-runner has no contract
  # document in text mode, so it scrapes counts out of this output and the
  # marker is its proof of origin. Text without it is MODULE_INVALID_TEXT and
  # the module's counts are discarded (modules/contract.json formats.text_marker).
  echo "UBS module: @DISPLAY@ (contract v2) v${VERSION} — ${PROJECT_DIR}"
  echo "Files: ${TOTAL_FILES} (${INCLUDE_EXT})"
  local i s file line code
  for i in "${!F_SEV[@]}"; do
    printf '\n[%s] %s (%s found) — %s\n' "${F_SEV[$i]}" "${F_TITLE[$i]}" "${F_COUNT[$i]}" "${F_RULE[$i]}"
    if [[ "$QUIET" -eq 0 ]]; then
      local shown=0
      IFS=$'\x1f' read -r -a samples <<<"${F_SAMPLES[$i]}"
      for s in "${samples[@]}"; do
        { read -r file; read -r line; read -r code; } < <(sample_parts "$s")
        printf '  %s:%s  %s\n' "$file" "$line" "$code"
        shown=$((shown + 1)); [[ "$shown" -ge 5 && "$VERBOSE" -eq 0 ]] && break
      done
    fi
  done
  # The meta-runner scrapes these exact labels in text mode; a module that
  # prints its counts in any other shape reports zeros however much it found.
  printf '\nSummary Statistics:\n'
  printf 'Files scanned: %s\n' "$TOTAL_FILES"
  printf 'Critical issues: %s\n' "$CRITICAL"
  printf 'Warning issues: %s\n' "$WARNING"
  printf 'Info items: %s\n' "$INFO"
}
render_json(){
  local i s file line code first=1 sfirst
  printf '{"language":"%s","project":"%s","files":%s,"critical":%s,"warning":%s,"info":%s,"timestamp":"%s","status":"ok","findings":[' \
    "$LANGUAGE" "$(json_escape "$PROJECT_DIR")" "$TOTAL_FILES" "$CRITICAL" "$WARNING" "$INFO" "$(timestamp)"
  for i in "${!F_SEV[@]}"; do
    [[ "$first" -eq 1 ]] || printf ','
    first=0
    printf '{"title":"%s","rule":"%s","severity":"%s","count":%s,"samples":[' "$(json_escape "${F_TITLE[$i]}")" "${F_RULE[$i]}" "${F_SEV[$i]}" "${F_COUNT[$i]}"
    sfirst=1
    IFS=$'\x1f' read -r -a samples <<<"${F_SAMPLES[$i]}"
    for s in "${samples[@]}"; do
      { read -r file; read -r line; read -r code; } < <(sample_parts "$s")
      [[ "$sfirst" -eq 1 ]] || printf ','
      sfirst=0
      printf '{"file":"%s","line":%s,"code":"%s"}' "$(json_escape "$file")" "${line:-0}" "$(json_escape "$code")"
    done
    printf ']}'
  done
  printf ']}\n'
}
render_sarif(){
  local i s file line code first=1 level
  printf '{"$schema":"https://json.schemastore.org/sarif-2.1.0.json","version":"2.1.0","runs":[{"tool":{"driver":{"name":"ubs-%s","version":"%s"}},"results":[' "$LANGUAGE" "$VERSION"
  for i in "${!F_SEV[@]}"; do
    case "${F_SEV[$i]}" in critical) level=error;; warning) level=warning;; *) level=note;; esac
    IFS=$'\x1f' read -r -a samples <<<"${F_SAMPLES[$i]}"
    for s in "${samples[@]}"; do
      { read -r file; read -r line; read -r code; } < <(sample_parts "$s")
      [[ "$first" -eq 1 ]] || printf ','
      first=0
      printf '{"ruleId":"%s","level":"%s","message":{"text":"%s"},"locations":[{"physicalLocation":{"artifactLocation":{"uri":"%s"},"region":{"startLine":%s}}}]}' \
        "${F_RULE[$i]}" "$level" "$(json_escape "${F_TITLE[$i]}")" "$(json_escape "$file")" "${line:-1}"
    done
  done
  printf ']}]}\n'
}

emit(){
  case "$FORMAT" in
    json) render_json;;
    sarif) render_sarif;;
    *) render_text;;
  esac
}
if [[ -n "$OUTPUT_FILE" ]]; then emit | tee "$OUTPUT_FILE"; else emit; fi

if [[ "$CRITICAL" -gt 0 ]]; then exit 1; fi
if [[ "$FAIL_ON_WARNING" -eq 1 && "$WARNING" -gt 0 ]]; then exit 1; fi
exit 0
TEMPLATE
chmod +x "$MODULE"

render >"$FIXTURE_DIR/buggy/sample.${EXT1}" <<'TEMPLATE'
// buggy fixture for the @DISPLAY@ module: one dangerous call (critical) and one marker (info)
// TODO: replace this example with a real @DISPLAY@ program
result = eval(user_input)
TEMPLATE
render >"$FIXTURE_DIR/clean/sample.${EXT1}" <<'TEMPLATE'
// clean fixture for the @DISPLAY@ module: nothing the example checks flag
result = compute(user_input)
TEMPLATE
render >"$FIXTURE_DIR/README.md" <<'TEMPLATE'
# @DISPLAY@ fixtures

- `buggy/sample.@EXT1@` — must yield at least one critical (an eval-style call) and one info (a TODO marker); manifest case `@LANG@-buggy`.
- `clean/sample.@EXT1@` — must yield no critical; manifest case `@LANG@-clean`.

Replace both when the example checks in `modules/ubs-@LANG@.sh` become real detectors; every real rule needs a line in each fixture and a manifest expectation.
TEMPLATE

tmp_manifest="$(mktemp)"
jq --arg lang "$LANG_NAME" --arg display "$DISPLAY" '
  .cases += [
    {id: ($lang + "-buggy"), description: ($display + " buggy fixture: the example checks must report the eval-style call as critical."),
     path: ("test-suite/" + $lang + "/buggy"), language: $lang, tags: [$lang, "buggy"],
     args: ["--only=" + $lang], expect: {exit_code: "nonzero", totals: {critical: {min: 1}}}},
    {id: ($lang + "-clean"), description: ($display + " clean fixture: the example checks must stay quiet."),
     path: ("test-suite/" + $lang + "/clean"), language: $lang, tags: [$lang, "clean"],
     args: ["--only=" + $lang], expect: {exit_code: "zero", totals: {critical: {max: 0}}}}
  ]' "$MANIFEST" >"$tmp_manifest"
mv "$tmp_manifest" "$MANIFEST"

cat >&2 <<NEXT
created:
  $MODULE
  $FIXTURE_DIR/buggy/sample.${EXT1}
  $FIXTURE_DIR/clean/sample.${EXT1}
  $FIXTURE_DIR/README.md
appended manifest cases ${LANG_NAME}-buggy and ${LANG_NAME}-clean to $MANIFEST

not applied (do these by hand, they touch shared files):
  1. ubs: add "${LANG_NAME}" to ALL_LANGS and a detect_lang case for the extensions (${EXTS}).
  2. modules/contract.json: add the "${LANG_NAME}" entry (file, display, extensions, manifest_files, contract: 2)
     and run scripts/gen_module_readme.py; python3 scripts/check_docs_claims.py must pass.
  3. ./scripts/update_checksums.sh && ./scripts/update_sha256sums.sh (MODULE_CHECKSUMS gets the new module).
  4. Replace the example checks and fixtures with real detectors; run test-suite/run_all.sh.
NEXT
